name: Print Branch Name

on:
  workflow_call:
  workflow_dispatch:

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: 'echo "Branch name: ${{ github.ref_name }}"'